"""
Generate Pydantic BaseModel subclasses from i18n texts.yaml files.

Usage: python -m scripts.generate_i18n
"""

from pathlib import Path

from ruamel.yaml import YAML

CANONICAL_LANG = "ru"
HEADER = '''\
"""
This file is auto-generated by scripts/generate_i18n.py - DO NOT EDIT.
"""

from pydantic import BaseModel


'''


def snake_to_camel(name: str) -> str:
    return "".join(part.title() for part in name.split("_"))


def infer_type(
    value: object, field_name: str, classes: list[str], seen: set[str]
) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, str):
        return "str"
    if isinstance(value, list):
        if not value:
            return "list[str]"
        if isinstance(value[0], str):
            return "list[str]"
        if isinstance(value[0], dict):
            item_class = snake_to_camel(field_name.rstrip("s")) + "Item"
            emit_class(item_class, value[0], classes, seen)
            return f"list[{item_class}]"
    if isinstance(value, dict):
        cls = snake_to_camel(field_name) + "Texts"
        emit_class(cls, value, classes, seen)
        return cls
    return "str"


def emit_class(
    class_name: str, data: dict[str, object], classes: list[str], seen: set[str]
) -> None:
    if class_name in seen:
        return
    seen.add(class_name)
    fields = [
        f"    {key}: {infer_type(val, key, classes, seen)}" for key, val in data.items()
    ]
    body = "\n".join(fields) if fields else "    pass"
    classes.append(f"class {class_name}(BaseModel):\n{body}\n")


def generate(yaml_path: Path) -> None:
    yaml = YAML()
    with open(yaml_path) as fd:
        data: dict[str, object] = yaml.load(fd)

    classes: list[str] = []
    seen: set[str] = set()
    for section_key, section_data in data.items():
        if not isinstance(section_data, dict):
            continue
        lang_data = section_data.get(CANONICAL_LANG) or next(
            iter(section_data.values())
        )
        root_class = snake_to_camel(section_key) + "Texts"
        emit_class(root_class, lang_data, classes, seen)

    out = yaml_path.parent / "_generated.py"
    out.write_text(HEADER + "\n\n".join(classes))
    print(f"  wrote {out.relative_to(Path.cwd())}")


def main() -> None:
    root = Path(__file__).parent.parent / "app"
    for yaml_path in sorted(root.rglob("i18n/texts.yaml")):
        print(f"processing {yaml_path.relative_to(Path.cwd())}")
        generate(yaml_path)


if __name__ == "__main__":
    main()
