name: backend

on:
  push:
    branches:
      - main
    paths-ignore:
      - packages/sdk/**
      - packages/webapp/**
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/backend

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5443:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: packages/backend/uv.lock
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --locked

      - name: Run lint
        run: uv run task lint

      - name: Run mypy
        run: uv run task mypy

      - name: Run tests
        run: uv run task test

  deploy:
    name: deploy 🚀
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: deploy
        name: Deploy
        run: |
          echo "Deploying..."
      - name: Notify on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_UPDATES_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ TGWebApp[backend]. Deploy failed

            Commit message: ${{ github.event.commits[0].message }}
            https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}
      - name: Notify on success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_UPDATES_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ TGWebApp[backend]. Deploy succeed

            Commit message: ${{ github.event.commits[0].message }}
            https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}
